name: CI

on:
  push:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Carregar Codigo do Repositorio
      uses: actions/checkout@v2
    
    - name: Ativando ambiente NodeJS
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12.x

    - name: Instalar Dependencias
      run: yarn
     
    - name: Rodar Build
      run: yarn build
    
    - name: Copiando arquivos para Digital Ocean via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSh_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/gobarber-backend"
      
    - name: Instalando dependencias, Migrations e Restartando NodeJS na Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSh_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/gobarber-backend
          yarn
          ./node_modules/.bin/typeorm migrations:run
          pm2 restart gobarber-api
    
